### ISSUE TITLE
 EBB SB2209 CAN Prevents Fan cover to be flush

### ISSUE THREAD

**Issue by Shan723** [JaredC01/Galileo2#27]
Hi I purchased a  EBB SB2209 CAN on Amazon but when installing the front cover fan it doesn't land lay flush to the front body and I think its due to board EBB SB2209 CAN sticking out more.
![20231229_093542](https://github.com/JaredC01/Galileo2/assets/146158066/efbb13ab-9e1c-49bc-a2a7-b762da6bb8a2)
![20231229_093546](https://github.com/JaredC01/Galileo2/assets/146158066/0e12fe26-d258-41b6-9c72-f48a17757029)
![20231229_093556](https://github.com/JaredC01/Galileo2/assets/146158066/e61afbf1-f0a1-4bd8-b517-339a59e4fe01)

**Comment by clau0086** [comment]
I'm having the same problem with the EBB SB2209 RP2040.  It's not as bad as yours.  I think moving the mounts back about 0.65mm would solve the problem.
![20231231_101959](https://github.com/JaredC01/Galileo2/assets/13812830/7c95c68e-1ea1-452b-a92a-f4e6bbc271fe)

**Comment by Hulign** [comment]
I don’t have any problem with the SB2240 this is the twinsor body but I have tried a couple others with no issue. 
You could always heat up the inserts and move them over a smidge.


![image](https://github.com/JaredC01/Galileo2/assets/151494467/29c68829-0797-4f20-9bf3-84f63a7768c1)

**Comment by clau0086** [comment]
Hulign - I though your idea was worth a try and it worked.  The front fits flush and the USB port has been moved a reasonable distance from the stepper.  The holes opened up a bit too much and I had to fill in with epoxy to prevent the brass inserts from spinning.  It looks like I'm going to need to edit the STL's or wait for an official update.  Thanks!
![Uploading 20231231_182949.jpg…]()

**Comment by clau0086** [comment]
![Uploading 20240101_094823_HDR.jpg…]()

**Comment by clau0086** [comment]
![20231231_182949](https://github.com/JaredC01/Galileo2/assets/13812830/f4b49b55-51e0-445b-a5a4-bf0201037041)

**Comment by clau0086** [comment]
![20240101_094823_HDR](https://github.com/JaredC01/Galileo2/assets/13812830/0f22e49c-727b-4958-8c22-37fca29f9a1c)

**Comment by JaredC01** [comment]
The board mounts are in the same location as CW2, so they should work as-is if they were working on CW2.  I will say, there's a bit of adjustment / flexibility in the board mount itself, so my suggestion is to leave the board mount screws slightly loose, push the SB front on, then tighten down the board with the front in place.  That should give the best chance of a good seat.

**Comment by clau0086** [comment]
I wonder if BTT didn't locate the holes correctly.  It just didn't seem right as it was.

**Comment by JKtech3D** [comment]
Everything lined up perfectly for me with almost no space between the USB and motor.

**Comment by Shan723** [comment]
I redid this again and it all fits, leaving the screws loose helped
