### ISSUE TITLE
G2E - collision SB2209 with stepper

### ISSUE THREAD

**Issue by Asica10** [JaredC01/Galileo2#33]
There is collision between SB2209 USB port and stepper motor. Potential solution can be move around 1-2mm sb2009 backward.
![IMG20240105205515](https://github.com/JaredC01/Galileo2/assets/52717193/3b6d1b1a-8da7-4eb0-af99-1845461d250b)

**Comment by Surion79** [comment]
is this an official LDO kit? i combined a SB2240 (same size) with the official LDO kit and i do not have this kind of issue

**Comment by gamkiller77** [comment]
I just mounted mine and it just touched a bit.

**Comment by JaredC01** [comment]
Added a bit of clearance to release version.  Closing, but reopen if you find this is still and issue.
