### ISSUE TITLE
G2Z Kit RevB - Bearings F623-2RS

### ISSUE THREAD

**Issue by aka-Ebo** [JaredC01/Galileo2#35]
Hi,
i have the Galileo 2 Z Drive Kit (RevB) and inside the box there are 2pc bearings F623-2RS. I dont see any use of them.
For what are they needed?

Greetings
aka_Ebo

**Comment by TamaBaka** [comment]
Saw them, but I didn't need to use them for the G2Z, but I notice that the G2E kit uses those bearings.

So spare parts, maybe.

**Comment by JaredC01** [comment]
They're used for Micron to fit the 20T pulley on G2 to the 16T pulleys on Micron.
