### ISSUE TITLE
Not a design issue, but where to get that special extruder gear?

### ISSUE THREAD

**Issue by Hoeby** [JaredC01/Galileo2#43]
I want to build the galileo 2.
Have a lot of parts in stock, but not the special 16mm extruder gear.

Where could i but only the gear?
Only found are the complete sets

**Comment by JaredC01** [comment]
LDO will have parts available in the near future.  I can't give a specific timeline as it's up to their supplier.  I'll update with a link when I have one.

**Comment by stefi01** [comment]
[](url)https://www.fabreeko.com/search?type=product%2Cpage%2Carticle&q=Galileo2
