### ISSUE TITLE
[G2E] Changelog from public beta?

### ISSUE THREAD

**Issue by Alohacajun** [JaredC01/Galileo2#44]
Have there been any major changes to G2E since the beta? 
Thanks for the official public release!

**Comment by JaredC01** [comment]
Everything has been adjusted in one way or another.  It warrants a reprint if you're questioning that.

**Comment by Stargaluxys** [comment]
Have any of the kit parts changed?

**Comment by JaredC01** [comment]
No, the kits are pretty well solidified at this point. The only thing of note is that there will be a 2mm drill bit included in future kits to assist with filament path clearance. In early beta there was also a change to add a couple of shims, but that was 4+ months ago now.

The core kit has remained the same.
